# Generated by Django 4.2.3 on 2023-09-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_convert_pass_expiry_user_to_one2one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cspreport',
            name='date_received',
            field=models.DateTimeField(help_text='When this report was received'),
        ),
        migrations.AlterField(
            model_name='passwordexpiry',
            name='password_expiry_date',
            field=models.DateTimeField(help_text="The date and time when the user's password expires. If this is empty, the password never expires.", null=True),
        ),
    ]
